model_config:
  target: submodules.instant_mesh.models.lrm_mesh.InstantMesh
  params:
    encoder_feat_dim: 768
    encoder_freeze: false
    encoder_model_name: facebook/dino-vitb16 # pretrained_models/dino-vitb16
    transformer_dim: 1024
    transformer_layers: 16
    transformer_heads: 16
    triplane_low_res: 32
    triplane_high_res: 64
    triplane_dim: 80
    rendering_samples_per_ray: 128
    grid_res: 128
    grid_scale: 2.1


infer_config:
  zero123plus: submodules/instant_mesh/zero123plus
  unet_path: pretrained_models/diffusion_pytorch_model.bin
  model_path: pretrained_models/instant_mesh_large.ckpt
  texture_resolution: 1024
  render_resolution: 512
  zero123plus_v12: sudo-ai/zero123plus-v1.2 # pretrained_models/zero123plus-v1.2